### ISSUE TITLE
Net core support?

### ISSUE THREAD

**Issue by nm17** [Sato-Isolated/MindLated#13]
Is there any plans on supporting net core? Right now it's giving me `System.BadImageFormatException: ".NET data directory RVA is 0"`

At `MindLated.MainWindow.Button_Click(object, System.Windows.RoutedEventArgs)`

**Comment by Sato-Isolated** [comment]
Hi, can you give me a sample please ?

**Comment by Sato-Isolated** [comment]
i don't know how net core work but you only need to obfuscate the dll no ?

**Comment by nm17** [comment]
> 
> 
> Hi, can you give me a sample please ?

Create a console net core project using Visual Studio and try to obfuscate it.

**Comment by Sato-Isolated** [comment]
Yeah but your code is in consoleapps1.dll so you just need to obfuscate the dll

**Comment by nm17** [comment]
Will check after
