### ISSUE TITLE
This is literally aura

### ISSUE THREAD

**Issue by Fadedexe** [Sato-Isolated/MindLated#24]

**Comment by Sato-Isolated** [comment]
?

**Comment by Fadedexe** [comment]
https://github.com/loomisntreal/Aura-.NET-Obfuscator

**Comment by Sato-Isolated** [comment]
https://github.com/loomisntreal/Aura-.NET-Obfuscator/pull/2/commits/96427e35fb194852e18ce7a88e63bc0783c96cf7 yes totally

**Comment by NullHF** [comment]
> https://github.com/loomisntreal/Aura-.NET-Obfuscator

lmao is capy pasted on this obfu by @Sato-Isolated

**Comment by BurntDog** [comment]
I see what you all are saying but, at least this project is being updated unlike the maybe original project.

**Comment by Sato-Isolated** [comment]
I'm the original project that not hard to check the commits date

**Comment by Sato-Isolated** [comment]
he just literally ctrl+h the whole project
