### ISSUE TITLE
file is not working after using String Encryption only

### ISSUE THREAD

**Issue by NotPrab** [Sato-Isolated/MindLated#3]
![SIkQ5O5fRL](https://user-images.githubusercontent.com/54489997/88615977-2ec0b900-d0bd-11ea-90c8-297fb3411f3f.png)

Sample : [Hmm.exe](https://cdn.discordapp.com/attachments/655744890956939284/759072140154109973/Hmm.exe)

**Comment by Sato-Isolated** [comment]
can you send me a sample please ^^ ?

**Comment by Sato-Isolated** [comment]
that's work now

**Comment by Sehyn** [comment]
As today, not working too.

**Comment by Sato-Isolated** [comment]
> As today, not working too.

can you send me an example (exe encrypted) without details I can't fix it

**Comment by DuckIsCool** [comment]
i was able to fix + fix anti tamper
