### ISSUE TITLE
Obsfucated executeables deleted on ran

### ISSUE THREAD

**Issue by xSute** [Sato-Isolated/MindLated#36]
When trying to run a obfuscated file, it deletes itself
Antivirus turned off / on doesn't matter

**Comment by Sato-Isolated** [comment]
This is because of the Antimanything class if you want to remove it go to this line and delete the line

https://github.com/Sato-Isolated/MindLated/blob/d29c06ebc526967fd2da45145a8f458201d12025/MindLated/MainWindow.xaml.cs#L188

I have to redo the ui to add the options I didn't put on it

**Comment by xSute** [comment]
Nah, now its just crashing on build, doesn't matter what Protection settings are on

**Comment by ChillGaming** [comment]
Where I can find obuscated file?
