### ISSUE TITLE
file is not working after using SOD only

### ISSUE THREAD

**Issue by NotPrab** [Sato-Isolated/MindLated#4]
![NF2fQ04gvQ](https://user-images.githubusercontent.com/54489997/88616115-75161800-d0bd-11ea-8fc2-bc7a3645b798.png)

**Comment by Sato-Isolated** [comment]
u need to upload the decoder.php to a site for this protection work 

for example : 
https://communitykeyv1.000webhostapp.com/Decoder.php?string={encrypted} 

my domain don't work anymore so u need to change it with another
