### ISSUE TITLE
How to compile this?

### ISSUE THREAD

**Issue by EmanAsAvcvb** [Sato-Isolated/MindLated#43]
I'm new in that. Help me please)

**Comment by Sato-Isolated** [comment]
you have to download Visual Studio https://visualstudio.microsoft.com/fr/vs/whatsnew/

**Comment by EmanAsAvcvb** [comment]
I know this. What file? .sln, .csproj. When I want to compile, I have problem (no debug or release folder) with .exe file. How i can compile your good project to .exe file? (Debbuging start isn't working)
