### ISSUE TITLE
The project is still alive?

### ISSUE THREAD

**Issue by DestroyerDarkNess** [Sato-Isolated/MindLated#44]
Hello, Good Protector. But are you still working on Him?

I say it scholause and don't see really important changes.

I have tried it with c# Console Applications and It's Going Well. But when testing it with Really Large Applications, It Fails.

What Really Interests Me is Renamer, and Don's Any Change in Him and Is Really Unstable. I tried it with One of My Really Big Applications and Did Not Work.

Even part of the part of 'Renamer' and none works.

- Rename Only Methods (Failure)
- Rename Only Namespace (It Works, Obviously.)
- Rename Only Classname (Failure.)
- Rename Only Properties (It Works, But It Causes UNEXPECTED CRASH.)

What I Mean with All This is that the Renamer function does not work for dirty applications.

IT Should Be Note The Tests Were With WPF C# and Winform VB.net. Demonstrating that it does not work at all in winform.

Forgive, if what I say is not understood. (I'm using google translate)

**Comment by Sato-Isolated** [comment]
the project on github I do not continue it and for the renamer does not support WPF and for the winform VB no idea I only tried with the winform C#

**Comment by DestroyerDarkNess** [comment]
Both C# and VB translate to IL Code when compiling. Therefore shouldn't it be the same? , only in .Net there are some extra classes. 

I have tried many different obfusters. (Kov.net, Astronfuck, etc ..) But the only one really stable was that of Confuserex. 

**Wouldn't you consider creating a Renamer based on the Confuserex code?**

**Comment by Sato-Isolated** [comment]
The difference between c# and vb once compiled is the <appname>.My class when rename is done it breaks the calls in class, I can fix this problem. 
![image](https://user-images.githubusercontent.com/12450341/208314020-e3038bab-6d9a-401d-9fca-72bf35dad767.png)

ConfuserEx is still the best free obfuscator

**Comment by DestroyerDarkNess** [comment]
Still without working :(

![image](https://user-images.githubusercontent.com/32405118/210281575-5ff18726-94cc-4a06-93c1-804f53e3f4a0.png)
