### ISSUE TITLE
Problem when using Int Obfuscation

### ISSUE THREAD

**Issue by NotPrab** [Sato-Isolated/MindLated#5]
after obfuscated file, It just ruin ConsoleColor
![hW7ufeAUNk](https://user-images.githubusercontent.com/54489997/88616415-4d737f80-d0be-11ea-81ca-d700df31dbf7.png)

**Comment by Sato-Isolated** [comment]
can you send me a sample please ^^ ?

**Comment by Sato-Isolated** [comment]
that's work now
