### ISSUE TITLE
Protected EXE Keeps getting detected as Malware?

### ISSUE THREAD

**Issue by mubaid** [Sato-Isolated/MindLated#7]
What is the bare minimum configuration that we should try with? I went with random protections (not all) and every time it was detected as Malware by McAfee.

Edit: Only string encryption works fine, by adding any other protection McAfee immediately deletes the file as a Malware. How to bypass this?

**Comment by Sato-Isolated** [comment]
hello if you try to protect a program take confuserEx or netguard with my obfuscator you won't be able to protect your program correctly and for the detections as Malware by McAfee it's false positives.
