### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Spache0** [Sato-Isolated/MindLated#8]
cannot be compiled.
always like this: https://prnt.sc/uh4j1e

**Comment by Sato-Isolated** [comment]
🤷 Hi, i can't help you with this only screen

**Comment by Spache123** [comment]
> 🤷 Hi, i can't help you with this only screen

you have discord?

**Comment by Sato-Isolated** [comment]
are you trying to obfuscate a big file ? and no i don't have discord

**Comment by Spache123** [comment]
> are you trying to obfuscate a big file ? and no i don't have discord

6 mb file

**Comment by Sato-Isolated** [comment]
that why he doesn't work u can only obfuscate lower size file

**Comment by Spache123** [comment]
> that why he doesn't work u can only obfuscate lower size file

the size is not big. medium size :/ and What should I do now?

**Comment by Sato-Isolated** [comment]
try another obfuscator [confuserEx](https://github.com/mkaring/ConfuserEx) or [NetGuard](https://netguard.io/)

**Comment by Spache123** [comment]
> try another obfuscator [confuserEx](https://github.com/mkaring/ConfuserEx) or [NetGuard](https://netguard.io/)

it unpack easily
